<?php

use WArslett\TableBuilder\ActionGroup;
use WArslett\TableBuilder\Renderer\Html\HtmlTableRendererInterface;
use WArslett\TableBuilder\Table;
use WArslett\TableBuilder\TableCell;

/**
 * @var HtmlTableRendererInterface $this
 * @var Table $table
 * @var TableCell<ActionGroup> $cell;
 */
?>

<div class="btn-group" role="group">
    <?php foreach ($cell->getValue()->getActions() as $action) : ?>
        <a
            href="<?= null !== $action->getRoute() ? $this->renderTableRoute($action->getRoute(), $action->getRouteParams()) : '#' ?>"
            class="btn btn-primary btn-sm"
        ><?= $action->getLabel() ?></a>
    <?php endforeach; ?>
</div>
