version: 2

jobs:
  build:
    machine: true
    steps:

      - checkout

      - run:
          name: "Pull PHP 7.3 Image"
          command: "docker pull php:7.3-cli"

      - run:
          name: "Build Testing Image"
          command: "docker build -t php:table-builder ."

      - run:
          name: "Install Composer Dependencies"
          command: "bin/composer install"

      - run:
          name: "Run Code Sniffer (Coding Standards)"
          command: "bin/phpcs"

      - run:
          name: "Run Psalm (PHP Static Analysis)"
          command: "bin/psalm --shepherd --stats"

      - run:
          name: "Run PHPUnit (Unit Tests)"
          command: "bin/phpunit --coverage-text --coverage-clover clover.xml --log-junit .circleci/test-results/phpunit/default.xml"

      - run:
          name: "Verify Code Coverage"
          command: "bin/coverage-check clover.xml 100"

      - store_test_results:
          path: ".circleci/test-results"

      - store_artifacts:
          path: clover.xml

      - store_artifacts:
          path: infection.log

      - run:
          name: "Send Report to Codecov"
          command: "bash <(curl -s https://codecov.io/bash)"