<?php

use WArslett\TableBuilder\Renderer\Html\HtmlTableRendererInterface;
use WArslett\TableBuilder\Table;

/**
 * @var HtmlTableRendererInterface $this
 * @var Table $table
 */
?>

<table>
    <thead>
    <tr>
        <?php foreach ($table->getHeadings() as $heading) : ?>
            <?= $this->renderTableHeading($table, $heading); ?>
        <?php endforeach; ?>
    </tr>
    </thead>
    <tbody>
        <?php foreach ($table->getRows() as $row) : ?>
            <?= $this->renderTableRow($table, $row); ?>
        <?php endforeach; ?>
    </tbody>
</table>
